In [9]:
import numpy as np

v1 = np.array([1,4,7])
v2 = np.array([[1],[4],[7]])
print(v1)
print(v2)

[1 4 7]
[[1]
 [4]
 [7]]


In [16]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Extract rows and cols

In [23]:
print(m[1,:],"\n")  # row 1
print(m[1:,:],"\n") # rows 1 and 2
print(m[:,0])       # col 1

[4 5 6] 

[[4 5 6]
 [7 8 9]] 

[1 4 7]


#### Multiply elements

In [26]:
x = np.array([1,2])
y = np.array([3,4])

z = x*y
print(z)

[3 8]


#### Matrix Multiplication

In [27]:
yy = np.array([[3],[4]])

zz = np.dot(x,yy)
print(zz)

[11]


In [30]:
#Run script vecMean.py

%run vecMean.py

4.0


#### Functions

In [58]:
def f(x):
    return x**2;

f(4)

16

In [53]:
from ffile import f

f(4)

NameError: name 'x' is not defined

In [46]:
def vec2min(v1, v2):
    v1min=np.min(v1)
    v2min=np.min(v2)
    return v1min, v2min

#### Loops

In [51]:
#while loop

def while_example():
    m=0
    i=1
    while(i<=5):
        m=m+3
        i=i+1
    return m

In [54]:
#for loop

m=0;

for i in range(5): #range(0,5) equivalent
    m=m+1

In [55]:
#vecMean without np

def vecMeanfunction2(v):
    vlength=len(v)
    total=0
    for i in range(vlength):
        total = total + v[i]
    return total/vlength

In [57]:
x = np.array([1,2,3,4,5])

vecMeanfunction2(x)

3.0

#### Conditional statements

In [60]:
def testf(num, thres):
    if (num>thres):
        return 1
    else:
        return 0

testf(1,0)

1